project:
  name: classic_methods
  seed: 42

validation_bool: true
validation_repetitions: 1

paths:
  config_path: config/paths.yaml

pipeline:
  config_path: C:\Users\lovro\Desktop\hackatoni\LUMEN2026\classic_methods\config\final_runtime\final_embedding_distance_katz_neighbors_5\20260509_105840\03_processed_3\pipeline.yaml

validation:
  config_path: C:\Users\lovro\Desktop\hackatoni\LUMEN2026\classic_methods\config\final_runtime\final_embedding_distance_katz_neighbors_5\20260509_105840\03_processed_3\validation.yaml
