data:
  csv_path: ${paths.processed_data_csv}

output:
  dir: C:\Users\lovro\Desktop\hackatoni\LUMEN2026\classic_methods\output_search\embedding_distance_katz_search\20260412_185555\run_0014

save_intermediates: false

stage1:
  config_path: config/recommendation/data_processing/preprocessing_impute_only.yaml

stage2:
  config_path: config/recommendation/embeddings/customer_features.yaml

stage3:
  config_path: config/recommendation/embeddings/vae_embedding.yaml

stage4:
  config_path: C:\Users\lovro\Desktop\hackatoni\LUMEN2026\classic_methods\config\search_runtime\embedding_distance_katz_search\20260412_185555\run_0014\from_embedding_distance.yaml

stage5:
  config_path: C:\Users\lovro\Desktop\hackatoni\LUMEN2026\classic_methods\config\search_runtime\embedding_distance_katz_search\20260412_185555\run_0014\katz.yaml
