project:
  name: classic_methods
  seed: 42

validation_bool: true
validation_repetitions: 1

paths:
  config_path: config/paths.yaml

pipeline:
  config_path: C:\Users\lovro\Desktop\hackatoni\LUMEN2026\classic_methods\config\final_runtime\final_embedding_distance_katz_ccw_1p0_datasets_246\20260509_163319\02_processed_4\pipeline.yaml

validation:
  config_path: C:\Users\lovro\Desktop\hackatoni\LUMEN2026\classic_methods\config\final_runtime\final_embedding_distance_katz_ccw_1p0_datasets_246\20260509_163319\02_processed_4\validation.yaml
