data:
  csv_path: C:\Users\lovro\Desktop\hackatoni\LUMEN_DS.csv

output:
  dir: C:\Users\lovro\Desktop\hackatoni\LUMEN2026\classic_methods\output_final\final_wide_recommendation_scores\20260509_173456\07_raw_fallback

save_intermediates: false

stage1:
  config_path: C:\Users\lovro\Desktop\hackatoni\LUMEN2026\classic_methods\config\final_runtime\final_wide_recommendation_scores\20260509_173456\07_raw_fallback\preprocessing.yaml

stage2:
  config_path: config/recommendation/embeddings/customer_features.yaml

stage3:
  config_path: config/recommendation/embeddings/vae_embedding.yaml

stage4:
  config_path: C:\Users\lovro\Desktop\hackatoni\LUMEN2026\classic_methods\config\final_runtime\final_wide_recommendation_scores\20260509_173456\07_raw_fallback\from_embedding_distance.yaml

stage5:
  config_path: C:\Users\lovro\Desktop\hackatoni\LUMEN2026\classic_methods\config\final_runtime\final_wide_recommendation_scores\20260509_173456\07_raw_fallback\katz.yaml
