data:
  csv_path: "C:/Users/dijan/Desktop/customer_features_500.csv"

output:
  dir: ${paths.output_dir}

save_intermediates: true

stage1:
  config_path: config/recommendation/embeddings/vae_embedding.yaml

stage4:
  config_path: config/recommendation/models/similarity_matrix/from_embedding_distance.yaml

stage5:
  config_path: config/recommendation/models/similarity_matrix/katz.yaml
