project:
  name: classic_methods
  seed: 42

validation_bool: true
validation_repetitions: 20

paths:
  config_path: config/paths.yaml

pipeline:
  config_path: config/recommendation/pipeline_base_baseline_method.yaml

validation:
  config_path: config/validation/validation_baseline_method.yaml