# saves latest model at the end of every epoch
model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  filename: epoch{epoch:02d}-step{step:06d}
  save_on_train_epoch_end: True

# saves top model according to val_loss
loss_val_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  filename: epoch{epoch:02d}-loss_val{loss_val:.4f}
  monitor: loss_val
  save_top_k: 1
  mode: min
