defaults:
  - data: digit_dataset.yaml
  - model: model.yaml
  - trainer: trainer.yaml
  - logger: mlflow.yaml
  - callbacks: callbacks.yaml
  - paths: paths.yaml
  - hydra: hydra.yaml
  - _self_

experiment_name: BasicCNN
